In [3]:
import torch
import torchvision.models as models

In [43]:
model = models.densenet121(pretrained=False)

In [44]:
out = model.features(torch.rand(1, 3, 224, 224))

In [46]:
out.shape

torch.Size([1, 1024, 7, 7])

In [10]:
!pip install torchxrayvision

     |████████████████████████████████| 29.0 MB 654 kB/s            


In [4]:
import torchxrayvision as xrv

In [5]:
model = xrv.models.DenseNet(weights="densenet121-res224-all")

In [48]:
output = model.features(torch.rand(1, 1, 224, 224))

In [49]:
output.shape

torch.Size([1, 1024, 7, 7])

In [54]:
output = model(torch.rand(1, 1, 224, 224))

In [55]:
output.shape

torch.Size([1, 18])

In [3]:
model2 = xrv.models.ResNet(weights="resnet50-res512-all")

In [ ]:
output2 = model.features()

In [8]:
import skimage, torch, torchvision

In [9]:
# Prepare the image:
img = skimage.io.imread("/mnt/data/mimic-cxr-jpg/images/p15/p15528228/s53078415/157febc5-ee2b7092-93d96d3d-3b125ac7-7e7795a0.jpg")

In [10]:
xrv.datasets.normalize(img, 255)

array([[-951.71765, -951.71765, -951.71765, ..., -951.71765, -951.71765,
        -951.71765],
       [-951.71765, -951.71765, -951.71765, ..., -951.71765, -951.71765,
        -951.71765],
       [-951.71765, -951.71765, -951.71765, ..., -951.71765, -951.71765,
        -951.71765],
       ...,
       [ 935.6549 ,  935.6549 ,  935.6549 , ...,  726.83923,  726.83923,
         734.8706 ],
       [ 935.6549 ,  935.6549 ,  935.6549 , ...,  718.80786,  726.83923,
         734.8706 ],
       [ 935.6549 ,  935.6549 ,  935.6549 , ...,  718.80786,  726.83923,
         742.902  ]], dtype=float32)

In [7]:
transform = torchvision.transforms.Compose([xrv.datasets.XRayCenterCrop(),xrv.datasets.XRayResizer(512)])

In [28]:
transform_224 = torchvision.transforms.Compose([
    skimage.io.imread,
    lambda x: xrv.datasets.normalize(x, 255, True),
    xrv.datasets.XRayResizer(224, 'cv2'),
    torch.from_numpy,
])

Setting XRayResizer engine to cv2 could increase performance.


In [30]:
transform_224("/mnt/data/mimic-cxr-jpg/images/p15/p15528228/s53078415/157febc5-ee2b7092-93d96d3d-3b125ac7-7e7795a0.jpg")

tensor([[[-951.7175, -951.7175, -951.7175,  ..., -972.1470, -964.6891,
          -951.9886],
         [-951.7175, -951.7175, -951.7175,  ..., -983.1025, -974.7338,
          -952.6588],
         [-951.7175, -951.7175, -951.7175,  ..., -983.8208, -981.5068,
          -953.0499],
         ...,
         [ 916.1978,  903.0844,  887.3856,  ...,  666.7125,  676.9722,
           726.6732],
         [ 920.6207,  906.9968,  897.0676,  ...,  679.0884,  683.1500,
           716.5581],
         [ 924.8251,  911.6147,  896.3547,  ...,  697.0203,  699.2075,
           715.7028]]])

In [26]:
out = model(transform_224(img).unsqueeze(0))

In [27]:
out

tensor([[0.3448, 0.1303, 0.5567, 0.2469, 0.0258, 0.5010, 0.3803, 0.1562, 0.0997,
         0.0818, 0.0284, 0.5020, 0.4597, 0.0009, 0.1433, 0.4232, 0.0990, 0.0717]],
       grad_fn=<IndexPutBackward0>)

In [1]:
import cv2

In [8]:
img2 = xrv.datasets.normalize(img, 255)

In [9]:
img2.reshape((1, *img2.shape)).shape

(1, 3056, 2544)

In [10]:
img3 = transform(img2.reshape((1, *img2.shape)))
img3.shape

(1, 512, 512)

In [11]:
img3

array([[[ -596.81866,  -648.34467,  -632.9938 , ...,  -910.9546 ,
          -911.384  ,  -810.72406],
        [ -565.1405 ,  -616.38574,  -606.57837, ..., -1016.2841 ,
         -1016.3205 ,  -904.0603 ],
        [ -519.299  ,  -539.28705,  -500.77597, ..., -1020.9186 ,
         -1017.12537,  -903.20734],
        ...,
        [ -317.54956,  -330.67065,  -329.13037, ...,  -887.33124,
          -887.974  ,  -792.6753 ],
        [ -317.05807,  -325.31073,  -317.80374, ...,  -886.56604,
          -886.65393,  -793.7825 ],
        [ -281.72067,  -287.83734,  -281.84308, ...,  -794.44116,
          -793.5761 ,  -712.57416]]], dtype=float32)

In [12]:
img4 = torch.from_numpy(img3)
img4.shape

torch.Size([1, 512, 512])

In [24]:
img4

tensor([[[ -596.8187,  -648.3447,  -632.9938,  ...,  -910.9546,
           -911.3840,  -810.7241],
         [ -565.1405,  -616.3857,  -606.5784,  ..., -1016.2841,
          -1016.3205,  -904.0603],
         [ -519.2990,  -539.2870,  -500.7760,  ..., -1020.9186,
          -1017.1254,  -903.2073],
         ...,
         [ -317.5496,  -330.6707,  -329.1304,  ...,  -887.3312,
           -887.9740,  -792.6753],
         [ -317.0581,  -325.3107,  -317.8037,  ...,  -886.5660,
           -886.6539,  -793.7825],
         [ -281.7207,  -287.8373,  -281.8431,  ...,  -794.4412,
           -793.5761,  -712.5742]]])

In [27]:
(torch.rand(1, 1, 512, 512) - 0.5) * 2048

tensor(-0.1228)

In [33]:
model2((torch.rand(1, 1, 512, 512) - 0.5) * 2048)

torch.Size([1, 18])

In [16]:
out.shape, out

(torch.Size([1, 2048]),
 tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<ReshapeAliasBackward0>))

In [83]:
model2.model

ResNet(
  (conv1): Conv2d(1, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [35]:
def _torchxrayvision_resnet_modified_forward(self, x):
    # x = fix_resolution(x, 512, self)
    # warn_normalization(x)

    x = self.model.conv1(x)
    x = self.model.bn1(x)
    x = self.model.relu(x)
    x = self.model.maxpool(x)

    x = self.model.layer1(x)
    x = self.model.layer2(x)
    x = self.model.layer3(x)
    x = self.model.layer4(x)
    local_features = x

    x = self.model.avgpool(x)
    x = torch.flatten(x, 1)
    global_features = x
    
    return global_features, local_features

model2.forward2 = _torchxrayvision_resnet_modified_forward.__get__(model2)

In [36]:
model2.features(img4.view(1, *img4.shape))

tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<ReshapeAliasBackward0>)

In [37]:
out = model2.forward2(img4.view(1, *img4.shape))

In [39]:
out[0].shape, out[0].sum()

(torch.Size([1, 2048]), tensor(35.4955, grad_fn=<SumBackward0>))

In [42]:
out[1].shape, out[1].sum()

(torch.Size([1, 2048, 16, 16]), tensor(9086.8457, grad_fn=<SumBackward0>))

In [103]:
out2

(tensor([[0., 0., 0.,  ..., 0., 0., 0.]], grad_fn=<ReshapeAliasBackward0>),
 tensor([[[[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],
 
          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],
 
          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           ...,
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0., 0., 0.]],
 
          ...,
 
          [[0., 0., 0.,  ..., 0., 0., 0.],
           [0., 0., 0.,  ..., 0.,

In [85]:
import torch.nn as nn

In [86]:
model2_aux = nn.Sequential(*list(model2.model.children())[:-1])

In [91]:
model2_aux(img4.view(1, *img4.shape)).shape

torch.Size([1, 2048, 1, 1])

In [ ]:
img = xrv.datasets.normalize(img, 255) # convert 8-bit image to [-1024, 1024] range
img = img.mean(2)[None, ...] # Make single color channel

transform = torchvision.transforms.Compose([xrv.datasets.XRayCenterCrop(),xrv.datasets.XRayResizer(224)])

In [31]:
ae = xrv.autoencoders.ResNetAE(weights="101-elastic")

If this fails you can run `wget https://github.com/mlmed/torchxrayvision/releases/download/v1/nihpcrsnamimic_ch-resnet101-2-ae-test2-elastic-e250.pt -O /home/pamessina/.torchxrayvision/models_data/nihpcrsnamimic_ch-resnet101-2-ae-test2-elastic-e250.pt`
[██████████████████████████████████████████████████]


In [38]:
((torch.rand(1, 1, 512, 512) - 0.5) * 2048).shape

torch.Size([1, 1, 512, 512])

In [46]:
ae.encode((torch.rand(1, 1, 224, 224) - 0.5) * 2048).shape

torch.Size([1, 512, 3, 3])

In [45]:
ae.encode.named_parameters

AttributeError: 'function' object has no attribute 'named_parameters'